<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (!Schema::hasTable('loan_applications')) {
            return;
        }

        $now = now();

        $rows = [
            [
                'token' => 'HW-4X7TQ9KP',
                'full_name' => 'Kelvin Mutethia',
                'email' => 'kelvin.mutethia+01@harborwell.com',
                'phone_number' => '+447920100001',
                'identity_type' => 'national_id',
                'id_number' => 'LM112233N',
                'income' => 28000,
                'amount' => 4000,
                'term_months' => 6,
                'pay_period' => 'monthly',
                'purpose' => 'emergency',
                'status' => 'submitted',
                'status_updated_at' => $now->copy()->subDays(1),
                'processing_fee_due_at' => $now->copy()->addDays(3),
                'created_at' => $now->copy()->subDays(7),
                'updated_at' => $now->copy()->subDays(1),
            ],
            [
                'token' => 'HW-9G2WQ5RT',
                'full_name' => 'Chloe Benson',
                'email' => 'chloe.benson+02@harborwell.com',
                'phone_number' => '+447920100002',
                'identity_type' => 'passport',
                'id_number' => '240112233',
                'income' => 52000,
                'amount' => 14000,
                'term_months' => 12,
                'pay_period' => 'monthly',
                'purpose' => 'personal',
                'status' => 'approved',
                'status_updated_at' => $now->copy()->subDays(2),
                'processing_fee_due_at' => $now->copy()->addDays(1),
                'created_at' => $now->copy()->subDays(12),
                'updated_at' => $now->copy()->subDays(2),
            ],
            [
                'token' => 'HW-2MP7L4XZ',
                'full_name' => 'Samuel Kariuki',
                'email' => 'samuel.kariuki+03@harborwell.com',
                'phone_number' => '+447920100003',
                'identity_type' => 'driver_license',
                'id_number' => 'JAMES801010A99BB00',
                'income' => 46000,
                'amount' => 22000,
                'term_months' => 18,
                'pay_period' => 'monthly',
                'purpose' => 'asset',
                'status' => 'processing_fee',
                'status_updated_at' => $now->copy()->subDays(3),
                'processing_fee_due_at' => $now->copy()->addDays(2),
                'created_at' => $now->copy()->subDays(10),
                'updated_at' => $now->copy()->subDays(3),
            ],
            [
                'token' => 'HW-6NC8J1VD',
                'full_name' => 'Aisha Noor',
                'email' => 'aisha.noor+04@harborwell.com',
                'phone_number' => '+447920100004',
                'identity_type' => 'national_id',
                'id_number' => 'PN223344P',
                'income' => 35000,
                'amount' => 7000,
                'term_months' => 6,
                'pay_period' => 'monthly',
                'purpose' => 'emergency',
                'status' => 'declined',
                'status_updated_at' => $now->copy()->subDays(5),
                'processing_fee_due_at' => $now->copy()->addDays(2),
                'created_at' => $now->copy()->subDays(9),
                'updated_at' => $now->copy()->subDays(5),
            ],
            [
                'token' => 'HW-7QR5M2HF',
                'full_name' => 'Oliver Grant',
                'email' => 'oliver.grant+05@harborwell.com',
                'phone_number' => '+447920100005',
                'identity_type' => 'passport',
                'id_number' => '351224680',
                'income' => 61000,
                'amount' => 26000,
                'term_months' => 24,
                'pay_period' => 'monthly',
                'purpose' => 'personal',
                'status' => 'submitted',
                'status_updated_at' => $now->copy()->subDays(4),
                'processing_fee_due_at' => $now->copy()->addDays(4),
                'created_at' => $now->copy()->subDays(8),
                'updated_at' => $now->copy()->subDays(4),
            ],
            [
                'token' => 'HW-1TJ6K9YU',
                'full_name' => 'Nadia Wambui',
                'email' => 'nadia.wambui+06@harborwell.com',
                'phone_number' => '+447920100006',
                'identity_type' => 'national_id',
                'id_number' => 'QR334455Q',
                'income' => 78000,
                'amount' => 52000,
                'term_months' => 12,
                'pay_period' => 'monthly',
                'purpose' => 'asset',
                'status' => 'approved',
                'status_updated_at' => $now->copy()->subDays(6),
                'processing_fee_due_at' => $now->copy()->addDays(1),
                'created_at' => $now->copy()->subDays(13),
                'updated_at' => $now->copy()->subDays(6),
            ],
            [
                'token' => 'HW-8VP3S2LA',
                'full_name' => 'Benjamin Otieno',
                'email' => 'ben.otieno+07@harborwell.com',
                'phone_number' => '+447920100007',
                'identity_type' => 'driver_license',
                'id_number' => 'SMITH801212B55CC11',
                'income' => 39000,
                'amount' => 9500,
                'term_months' => 9,
                'pay_period' => 'monthly',
                'purpose' => 'emergency',
                'status' => 'submitted',
                'status_updated_at' => $now->copy()->subDays(2),
                'processing_fee_due_at' => $now->copy()->addDays(5),
                'created_at' => $now->copy()->subDays(6),
                'updated_at' => $now->copy()->subDays(2),
            ],
            [
                'token' => 'HW-5DZ4R8QN',
                'full_name' => 'Rachel Kibet',
                'email' => 'rachel.kibet+08@harborwell.com',
                'phone_number' => '+447920100008',
                'identity_type' => 'passport',
                'id_number' => '467889120',
                'income' => 88000,
                'amount' => 60000,
                'term_months' => 18,
                'pay_period' => 'monthly',
                'purpose' => 'business',
                'status' => 'processing_fee',
                'status_updated_at' => $now->copy()->subDays(2),
                'processing_fee_due_at' => $now->copy()->addDays(2),
                'created_at' => $now->copy()->subDays(11),
                'updated_at' => $now->copy()->subDays(2),
            ],
            [
                'token' => 'HW-3HF7B2MC',
                'full_name' => 'Irene Achieng',
                'email' => 'irene.achieng+09@harborwell.com',
                'phone_number' => '+447920100009',
                'identity_type' => 'national_id',
                'id_number' => 'ST445566S',
                'income' => 47000,
                'amount' => 15000,
                'term_months' => 12,
                'pay_period' => 'monthly',
                'purpose' => 'personal',
                'status' => 'submitted',
                'status_updated_at' => $now->copy()->subDays(7),
                'processing_fee_due_at' => $now->copy()->addDays(3),
                'created_at' => $now->copy()->subDays(15),
                'updated_at' => $now->copy()->subDays(7),
            ],
            [
                'token' => 'HW-9KT2X6PL',
                'full_name' => 'Victor Mwangi',
                'email' => 'victor.mwangi+10@harborwell.com',
                'phone_number' => '+447920100010',
                'identity_type' => 'passport',
                'id_number' => '598877663',
                'income' => 52000,
                'amount' => 9000,
                'term_months' => 9,
                'pay_period' => 'monthly',
                'purpose' => 'emergency',
                'status' => 'approved',
                'status_updated_at' => $now->copy()->subDays(8),
                'processing_fee_due_at' => $now->copy()->addDays(1),
                'created_at' => $now->copy()->subDays(16),
                'updated_at' => $now->copy()->subDays(8),
            ],
            [
                'token' => 'HW-4LQ8N1ZR',
                'full_name' => 'Beatrice Naliaka',
                'email' => 'beatrice.naliaka+11@harborwell.com',
                'phone_number' => '+447920100011',
                'identity_type' => 'national_id',
                'id_number' => 'UV556677U',
                'income' => 36000,
                'amount' => 11000,
                'term_months' => 12,
                'pay_period' => 'monthly',
                'purpose' => 'personal',
                'status' => 'declined',
                'status_updated_at' => $now->copy()->subDays(5),
                'processing_fee_due_at' => $now->copy()->addDays(2),
                'created_at' => $now->copy()->subDays(9),
                'updated_at' => $now->copy()->subDays(5),
            ],
            [
                'token' => 'HW-2XJ9C5MB',
                'full_name' => 'Kevin Mutua',
                'email' => 'kevin.mutua+12@harborwell.com',
                'phone_number' => '+447920100012',
                'identity_type' => 'passport',
                'id_number' => '880011223',
                'income' => 43000,
                'amount' => 25000,
                'term_months' => 24,
                'pay_period' => 'monthly',
                'purpose' => 'asset',
                'status' => 'submitted',
                'status_updated_at' => $now->copy()->subDays(2),
                'processing_fee_due_at' => $now->copy()->addDays(4),
                'created_at' => $now->copy()->subDays(7),
                'updated_at' => $now->copy()->subDays(2),
            ],
            [
                'token' => 'HW-7BQ3V6TA',
                'full_name' => 'Nancy Adhiambo',
                'email' => 'nancy.adhiambo+13@harborwell.com',
                'phone_number' => '+447920100013',
                'identity_type' => 'driver_license',
                'id_number' => 'BROWN801212C88DD22',
                'income' => 68000,
                'amount' => 52000,
                'term_months' => 18,
                'pay_period' => 'monthly',
                'purpose' => 'business',
                'status' => 'processing_fee',
                'status_updated_at' => $now->copy()->subDays(3),
                'processing_fee_due_at' => $now->copy()->addDays(2),
                'created_at' => $now->copy()->subDays(12),
                'updated_at' => $now->copy()->subDays(3),
            ],
            [
                'token' => 'HW-6FX1R8QC',
                'full_name' => 'Samuel Karanja',
                'email' => 'samuel.karanja+14@harborwell.com',
                'phone_number' => '+447920100014',
                'identity_type' => 'national_id',
                'id_number' => 'WX667788W',
                'income' => 57000,
                'amount' => 19000,
                'term_months' => 15,
                'pay_period' => 'monthly',
                'purpose' => 'personal',
                'status' => 'submitted',
                'status_updated_at' => $now->copy()->subDays(6),
                'processing_fee_due_at' => $now->copy()->addDays(3),
                'created_at' => $now->copy()->subDays(13),
                'updated_at' => $now->copy()->subDays(6),
            ],
            [
                'token' => 'HW-1VM9P4GD',
                'full_name' => 'Fiona Mugo',
                'email' => 'fiona.mugo+15@harborwell.com',
                'phone_number' => '+447920100015',
                'identity_type' => 'passport',
                'id_number' => '991122334',
                'income' => 45000,
                'amount' => 14000,
                'term_months' => 10,
                'pay_period' => 'monthly',
                'purpose' => 'emergency',
                'status' => 'approved',
                'status_updated_at' => $now->copy()->subDays(7),
                'processing_fee_due_at' => $now->copy()->addDays(1),
                'created_at' => $now->copy()->subDays(15),
                'updated_at' => $now->copy()->subDays(7),
            ],
            [
                'token' => 'HW-8RJ2H5WD',
                'full_name' => 'Hassan Noor',
                'email' => 'hassan.noor+16@harborwell.com',
                'phone_number' => '+447920100016',
                'identity_type' => 'national_id',
                'id_number' => 'YZ778899Y',
                'income' => 61000,
                'amount' => 30000,
                'term_months' => 18,
                'pay_period' => 'monthly',
                'purpose' => 'asset',
                'status' => 'processing_fee',
                'status_updated_at' => $now->copy()->subDays(4),
                'processing_fee_due_at' => $now->copy()->addDays(2),
                'created_at' => $now->copy()->subDays(10),
                'updated_at' => $now->copy()->subDays(4),
            ],
            [
                'token' => 'HW-5PG7T3XM',
                'full_name' => 'Olivia Atieno',
                'email' => 'olivia.atieno+17@harborwell.com',
                'phone_number' => '+447920100017',
                'identity_type' => 'driver_license',
                'id_number' => 'WHITE901010D77EE33',
                'income' => 39000,
                'amount' => 8000,
                'term_months' => 6,
                'pay_period' => 'monthly',
                'purpose' => 'personal',
                'status' => 'declined',
                'status_updated_at' => $now->copy()->subDays(5),
                'processing_fee_due_at' => $now->copy()->addDays(2),
                'created_at' => $now->copy()->subDays(11),
                'updated_at' => $now->copy()->subDays(5),
            ],
            [
                'token' => 'HW-3JK6L9NR',
                'full_name' => 'Joseph Njoroge',
                'email' => 'joseph.njoroge+18@harborwell.com',
                'phone_number' => '+447920100018',
                'identity_type' => 'passport',
                'id_number' => '334455668',
                'income' => 72000,
                'amount' => 65000,
                'term_months' => 24,
                'pay_period' => 'monthly',
                'purpose' => 'business',
                'status' => 'submitted',
                'status_updated_at' => $now->copy()->subDays(2),
                'processing_fee_due_at' => $now->copy()->addDays(4),
                'created_at' => $now->copy()->subDays(8),
                'updated_at' => $now->copy()->subDays(2),
            ],
            [
                'token' => 'HW-9MD4Q1SV',
                'full_name' => 'Agnes Mwende',
                'email' => 'agnes.mwende+19@harborwell.com',
                'phone_number' => '+447920100019',
                'identity_type' => 'national_id',
                'id_number' => 'AC889900A',
                'income' => 47000,
                'amount' => 16000,
                'term_months' => 12,
                'pay_period' => 'monthly',
                'purpose' => 'personal',
                'status' => 'processing_fee',
                'status_updated_at' => $now->copy()->subDays(3),
                'processing_fee_due_at' => $now->copy()->addDays(1),
                'created_at' => $now->copy()->subDays(9),
                'updated_at' => $now->copy()->subDays(3),
            ],
            [
                'token' => 'HW-2TR8Z6KC',
                'full_name' => 'Martin Were',
                'email' => 'martin.were+20@harborwell.com',
                'phone_number' => '+447920100020',
                'identity_type' => 'passport',
                'id_number' => '778899002',
                'income' => 52000,
                'amount' => 28000,
                'term_months' => 18,
                'pay_period' => 'monthly',
                'purpose' => 'asset',
                'status' => 'approved',
                'status_updated_at' => $now->copy()->subDays(6),
                'processing_fee_due_at' => $now->copy()->addDays(1),
                'created_at' => $now->copy()->subDays(14),
                'updated_at' => $now->copy()->subDays(6),
            ],
        ];

        DB::table('loan_applications')->insert($rows);
    }

    public function down(): void
    {
        if (!Schema::hasTable('loan_applications')) {
            return;
        }

        $tokens = [
            'HW-4X7TQ9KP',
            'HW-9G2WQ5RT',
            'HW-2MP7L4XZ',
            'HW-6NC8J1VD',
            'HW-7QR5M2HF',
            'HW-1TJ6K9YU',
            'HW-8VP3S2LA',
            'HW-5DZ4R8QN',
            'HW-3HF7B2MC',
            'HW-9KT2X6PL',
            'HW-4LQ8N1ZR',
            'HW-2XJ9C5MB',
            'HW-7BQ3V6TA',
            'HW-6FX1R8QC',
            'HW-1VM9P4GD',
            'HW-8RJ2H5WD',
            'HW-5PG7T3XM',
            'HW-3JK6L9NR',
            'HW-9MD4Q1SV',
            'HW-2TR8Z6KC',
        ];

        DB::table('loan_applications')->whereIn('token', $tokens)->delete();
    }
};
